# Generated by Django 4.0.3 on 2022-08-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Khalti', 'Khalti')], default='Khalti', max_length=20),
        ),
    ]
